name: test

on:
  push:
    paths-ignore:
      - '**README*'
  pull_request:
    paths-ignore:
      - '**README*'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        emacs_version:
          - "26.3"
          - "27.2"
          - "28.1"
          - snapshot
    steps:
      - name: Set up Emacs
        uses: purcell/setup-emacs@master
        with:
          version: ${{matrix.emacs_version}}

      - name: Check out relint
        uses: actions/checkout@v2
        with:
          path: relint

      - name: Check out xr
        uses: actions/checkout@v2
        with:
          repository: mattiase/xr
          path: xr

      - name: Byte-compile
        run: make -C relint build

      - name: Test
        run: make -C relint check
